### ISSUE TITLE
Remote user connection fail

### ISSUE THREAD

**Issue by DF1CHB** [F4FXL/DStarGateway#13]
[INFO   ] Remote control user has failed login authentication

**Comment by F4FXL** [comment]
Fixed https://github.com/F4FXL/DStarGateway/commit/43304c48b7c6e5c63404ae89bb5b2c3a393cce21

**Comment by F4FXL** [comment]
Fixed with https://github.com/F4FXL/DStarGateway/commit/43304c48b7c6e5c63404ae89bb5b2c3a393cce21
