### ISSUE TITLE
Loaded 0 of 0 DExtra hosts / Loaded 0 of 0 DCS hosts

### ISSUE THREAD

**Issue by DF1CHB** [F4FXL/DStarGateway#14]
[INFO   ] Loaded 0 of 0 DExtra hosts from /usr/local/share/dstargateway.d//Gateway_Hosts.txt

[INFO   ] Loaded 0 of 0 DCS hosts from /tmp/XLXHostFile_G1Iqej

Loading of DPlus Hosts fine.

[INFO   ] Loaded 1376 of 1378 DPlus hosts from /usr/local/share/dstargateway.d//DPlus_Hosts.txt

**Comment by F4FXL** [comment]
Gateway_Hosts.txt is a legacy from ircDDBGateway it was meant to contain only gateways, file is not included in the default setup hence the not loading.

If the XLXHostFile being downloaded properly ?

**Comment by DF1CHB** [comment]
> 
Apparently nothing from the TEMP file
[2022-01-05 11:44:14] [INFO   ] Loaded 0 of 0 DCS hosts from /tmp/XLXHostFile_tFwQ0Q

**Comment by F4FXL** [comment]
Actual bug, no XLX are loaded
