### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by TS6000** [F4FXL/DStarGateway#36]
g++ -W -O3 -Wall -Werror -std=c++17 -MMD -MD -c Daemon.cpp -o Daemon.o
Daemon.cpp: In static member function ‘static DAEMONIZE_RESULT CDaemon::daemonise(const string&, const string&)’:
Daemon.cpp:172:8: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
   write(m_pid_fd, str, strlen(str));
   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Makefile:9: recipe for target 'Daemon.o' failed
make[1]: *** [Daemon.o] Error 1
make[1]: Leaving directory '/opt/DStarGateway/BaseCommon'
Makefile:51: recipe for target 'BaseCommon/BaseCommon.a' failed
make: *** [BaseCommon/BaseCommon.a] Error 2

**Comment by F4FXL** [comment]
Hi,

Thanks for your report. Can you give more details about your environement?

**Comment by F4FXL** [comment]
Please share following information:
- os
- os version
- Are you trying to build stable or devlopment version ?

**Comment by F4FXL** [comment]
@TS6000  Can you try to build branch bugfix/36_Error1 ?
