### ISSUE TITLE
Fails build on Ubuntu without ENABLE_DEBUG

### ISSUE THREAD

**Issue by johnhays** [F4FXL/DStarGateway#40]
Daemon.cpp: In static member function ‘static DAEMONIZE_RESULT CDaemon::daemonise(const string&, const string&)’:
Daemon.cpp:172:22: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  172 |                 write(m_pid_fd, str, strlen(str));
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:9: Daemon.o] Error 1

**Comment by F4FXL** [comment]
Thanks for reporting this issue. What branch/tag are you trying to build?
What version of Ubuntu are you running?

**Comment by F4FXL** [comment]
Might also be related to : https://groups.io/g/OpenDV/message/1854
