### ISSUE TITLE
New make error

### ISSUE THREAD

**Issue by johnhays** [F4FXL/DStarGateway#46]
Daemon.cpp: In static member function ‘static DAEMONIZE_RESULT CDaemon::daemonise(const string&, const string&)’:
Daemon.cpp:172:22: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  172 |                 write(m_pid_fd, str, strlen(str));
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by F4FXL** [comment]
Is this master branch?

**Comment by johnhays** [comment]
May have been a branch, I performed a new clone and it built - I say close it.

**Comment by F4FXL** [comment]
Master branch is quite out date. I think I should release a new version soon in order to update it.
