### ISSUE TITLE
Failing Systemd Targets

### ISSUE THREAD

**Issue by johnhays** [F4FXL/DStarGateway#47]
[    0.888034] drop_monitor: Initializing network drop monitor service
[    6.440168] systemd[1]: /lib/systemd/system/dstargateway.service:3: Failed to add dependency on network.target,network-online.target, ignoring: Invalid argument
[    6.443849] systemd[1]: /lib/systemd/system/dsgwdashboard.service:3: Failed to add dependency on network.target,network-online.target, ignoring: Invalid argument
[    6.446901] systemd[1]: /lib/systemd/system/dgwtimeserver.service:3: Failed to add dependency on network.target,network-online.target, ignoring: Invalid argument
root@p2-ubu:/lib/systemd/system# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by johnhays** [comment]
I think this may be a failure on network-online.target as one of the ethernet. ports is a usb to ethernet adapter and may take longer to provision or is not recognized?

**Comment by F4FXL** [comment]
Is this only occuring on time server?
What does following command return ?
````
sudo systemctl list-units | grep network
````

**Comment by johnhays** [comment]
Go ahead and close for now.
