### ISSUE TITLE
DTMF not working  and dstargateway.service does not start

### ISSUE THREAD

**Issue by pa2snk** [F4FXL/DStarGateway#48]
I cannot start dstargateway.service i get a timeout.
Manualy can start dstargateway in usr/local/bin
i run bookworm 64 bit:

root@pi1snk:/home/pa2snk/DStarGateway# systemctl  start  dstargateway.service
Job for dstargateway.service failed because a timeout was exceeded.
See "systemctl status dstargateway.service" and "journalctl -xeu dstargateway.service" for details.
root@pi1snk:/home/pa2snk/DStarGateway# sudo systemctl status dstargateway
â— dstargateway.service - D-STAR Gateway Daemon
     Loaded: loaded (/lib/systemd/system/dstargateway.service; enabled; preset: enabled)
     Active: activating (start-pre) since Tue 2024-07-16 22:24:32 CEST; 1min 15s ago
  Cntrl PID: 516337 (bash)
      Tasks: 2 (limit: 448)
        CPU: 470ms
     CGroup: /system.slice/dstargateway.service
             â”œâ”€516337 /bin/bash -c "until host google.com; do sleep 1; done"
             â””â”€516487 sleep 1

Jul 16 22:25:37 pi1snk bash[516468]: /bin/bash: line 1: host: command not found
Jul 16 22:25:38 pi1snk bash[516470]: /bin/bash: line 1: host: command not found
Jul 16 22:25:39 pi1snk bash[516472]: /bin/bash: line 1: host: command not found
Jul 16 22:25:40 pi1snk bash[516474]: /bin/bash: line 1: host: command not found
Jul 16 22:25:41 pi1snk bash[516476]: /bin/bash: line 1: host: command not found
Jul 16 22:25:42 pi1snk bash[516478]: /bin/bash: line 1: host: command not found
Jul 16 22:25:43 pi1snk bash[516480]: /bin/bash: line 1: host: command not found
Jul 16 22:25:44 pi1snk bash[516482]: /bin/bash: line 1: host: command not found
Jul 16 22:25:45 pi1snk bash[516484]: /bin/bash: line 1: host: command not found
Jul 16 22:25:46 pi1snk bash[516486]: /bin/bash: line 1: host: command not found
root@pi1snk:/home/pa2snk/DStarGateway#

Also when starting manualy te program it wil not link automaticaly to a reflector.
When sending a dtmf command it wil connect to te same reflector as in the dstargateway.cfg
i checked the path to the ambe audio files and this is set ok.

2024-07-16 20:47:27] [INFO   ] Registered with auth.dstargateway.org using callsign PI1SNK
[2024-07-16 20:47:28] [ERROR  ] Cannot find the AMBE index for *linkingto*
[2024-07-16 20:47:28] [ERROR  ] Cannot find the AMBE index for *d*
[2024-07-16 20:47:28] [ERROR  ] Cannot find the AMBE index for *c*
[2024-07-16 20:47:28] [ERROR  ] Cannot find the AMBE index for *s*
[2024-07-16 20:47:28] [ERROR  ] Cannot find the AMBE index for *b*
[2024-07-16 20:47:31] [INFO   ] ircDDB did not reply within five seconds
[2024-07-16 20:47:32] [INFO   ] APRS Frame sent to IS ==> PI1SNK-B>APD5T3,TCPIP*,qAC,PI1SNK-BS:>Not linked
[2024-07-16 20:47:47] [INFO   ] APRS Frame sent to IS ==> PI1SNK-S>APD5T1,TCPIP*,qAC,PI1SNK-GS:;PI1SNK B *162047z5302.02ND00539.67EaRNG0022/A=000052 440 Voice 438.32500MHz -7.6000MHz
[2024-07-16 20:47:48] [INFO   ] APRS Frame sent to IS ==> PI1SNK-B>APD5T2,TCPIP*,qAC,PI1SNK-BS:!5302.02ND00539.67E&RNG0022/A=000052 440 Voice 438.32500MHz -7.6000MHz
[2024-07-16 20:50:54] [INFO   ] Link command from PI1SNK B to DCS007 B issued via DTMF by PA2SNK
[2024-07-16 20:50:54] [INFO   ] Link command from PI1SNK B to DCS007 B issued via DTMF by PA2SNK
[2024-07-16 20:50:54] [INFO   ] New DCS Protocol Handler now on port 30052.
[2024-07-16 20:50:54] [INFO   ] New DCS Protocol Handler now on port 30052.
[2024-07-16 20:50:54] [INFO   ] DCS ACK message received from DCS007 B
[2024-07-16 20:50:54] [INFO   ] DCS ACK message received from DCS007 B
[2024-07-16 20:50:54] [INFO   ] DCS link to DCS007 B established
[2024-07-16 20:50:54] [INFO   ] DCS link to DCS007 B established
[2024-07-16 20:50:54] [INFO   ] APRS Frame sent to IS ==> PI1SNK-B>APD5T3,TCPIP*,qAC,PI1SNK-BS:>Linking to DCS007 B

**Comment by F4FXL** [comment]
Hi,

The timeout in the service is caused by the host command being missing. The host command is used to check if the network is actually alive. It is an ugly trick, but I did not find a reliable way to do it the full systemd way.
Install package bind9-host should solve this issue.

Does linking over regular command work?
Did you install or using the makefile? Are you using dev version? 
Please also post your OS details

It looks like some file are missing:
```
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for linkingto
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for d
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for c
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for s
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for b
```
Also It seems like you are running DstarGateway alongside with ircddbgateway, is this on purpose? Are you running DStarGateway inside WPSD?

**Comment by pa2snk** [comment]
Thanks for the reply, i installed the bind9-host package this did the trick for starting as service.
I did a install using the makefile, no errors installing.
A normal link command with the ic91 and ic9700 work fine, i only get a cannot find the AMBE index for linked to.
But it does link to the reflector.

Did an install same way before on bulseye 32bit and is still working on another repeater site using a icom stack.(PI1DHR)

I have wpsd running on a hotspot for the holidays and have had a mixed system temporarily becouse i had to build a new repeater system for dstar, all is back to single use repeaters.
The hotspot is normaly off, the hotspot and mixed repeater are wpsd.

Here are my os details:

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Verzonden vanuit Mail voor Windows

Van: Geoffrey Merck
Verzonden: woensdag 17 juli 2024 06:49
Aan: F4FXL/DStarGateway
CC: pa2snk; Author
Onderwerp: Re: [F4FXL/DStarGateway] dstargateway.service does not start (Issue#48)

Hi,
The timeout in the service is caused by the host command being missing. The host command is used to check if the network is actually alive. It is an ugly trick, but I did not find a reliable way to do it the full systemd way.
Install package bind9-host should solve this issue.
Does linking over regular command work?
Did you install or using the makefile? Are you using dev version?
Please also post your OS details
It looks like some file are missing:
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for linkingto
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for d
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for c
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for s
[2024-07-16 20:47:28] [ERROR ] Cannot find the AMBE index for b
Also It seems like you are running DstarGateway alongside with ircddbgateway, is this on purpose? Are you running DStarGateway inside WPSD?

**Comment by F4FXL** [comment]
I started investigating, DTMF is broken

Can you please confirm the following:
DTMF is working on your Icom Stack
DTMF fails on your MMDVM

**Comment by pa2snk** [comment]
Dtmf works good here on both icom and homebrew repeater.

Verzonden vanuit Mail voor Windows

Van: Geoffrey Merck
Verzonden: woensdag 17 juli 2024 21:44
Aan: F4FXL/DStarGateway
CC: pa2snk; Author
Onderwerp: Re: [F4FXL/DStarGateway] DTMF not working and dstargateway.servicedoes not start (Issue #48)

I started investigating, DTMF is broken
Can you please confirm the following:
DTMF is working on your Icom Stack
DTMF fails on your MMDVM

**Comment by F4FXL** [comment]
Now you got me confused, or maybe my question was not clear...

Are you able to change reflector using DTMF on Icom stack?
Are you able to change reflector using DTMF on homebrew repeater ?

**Comment by F4FXL** [comment]
If changing reflector on Icom stack is working and not working on homebrew, it might be related to this issue here: https://github.com/g4klx/MMDVMHost/issues/702

**Comment by pa2snk** [comment]
Dtmf works ok on both systems.Op 17 jul. 2024 22:27 schreef Geoffrey Merck ***@***.***>:
Now you got me confused, or maybe my question was not clear...
Are you able to change reflector using DTMF on Icom stack?
Are you able to change reflector using DTMF on homebrew repeater ?

**Comment by pa2snk** [comment]
Only thing that is not working at the moment is the auto reflector.
On startup and after for example an half hour.
I have checked the path setting in dstargateway.cfg in this where the files are located.
These are the files i have in that directory:

***@***.***:/usr/local/share/dstargateway.d $ dir
CCS_Hosts.txt	  en_GB.indx  no_NO.ambe       TIME_en_GB.indx
DCS_Hosts.txt	  en_US.ambe  no_NO.indx       TIME_en_US.ambe
de_DE.ambe	  en_US.indx  pl_PL.ambe       TIME_en_US.indx
de_DE.indx	  es_ES.ambe  pl_PL.indx       TIME_fr_FR.ambe
DExtra_Hosts.txt  es_ES.indx  se_SE.ambe       TIME_fr_FR.indx
dk_DK.ambe	  fr_FR.ambe  se_SE.indx       TIME_se_SE.ambe
dk_DK.indx	  fr_FR.indx  TIME_de_DE.ambe  TIME_se_SE.indx
DPlus_Hosts.txt   it_IT.ambe  TIME_de_DE.indx
en_GB.ambe	  it_IT.indx  TIME_en_GB.ambe
***@***.***:/usr/local/share/dstargateway.d $

and my dstargateway.cfg:
# The configuration format is quite straight forward. It is organised in sections and key/value pairs.
# The order of the sections or key/values pairs inside the sections does not matter nor does casing.
# Boolean values can be set using true, false, 1 or 0
# Floating point values must use . (point) as decimal separator
[Gateway]
type=repeater		# repeater, hotspot, dongle. Defaults to repeater
callsign=pi1snk
address=0.0.0.0	        # this is the computer interface for the outgoing connection. Usually leave it blank and it will use whatever is avaiable.
icomAddress=172.16.0.20 
icomPort=20000          
hbAddress=127.0.0.1             #address to use for connecting to the homebrew repeaters (MMDVMHost, DStarRepeater), defaults to 127.0.0.1
hbPort=20010
latitude=53.033718
longitude=5.661130
description1=Repeater Sneek
description2=
url=
language=english_us              # valid values: english_uk, deutsch, dansk, francais, italiano, polski, english_us, espanol, svenska, nederlands_nl, nederlands_be, norsk, portugues

#up to 4 ircddb networks can be specified
[ircddb_1]
enabled=true
hostname=ircv4.openquad.net
username=pi1snk              # The ircDDB username defaults to the value defined for gateway callsign.
password=

[ircddb_2]
enabled=true
hostname=ircddb.net
username=pi1snk              # The ircDDB username defaults to the value defined for gateway callsign.
password=

[ircddb_3]
enabled=false
hostname=
username=CHNGME         # The ircDDB username defaults to the value defined for gateway callsign.
password=

[ircddb_4]
enabled=false
hostname=
username=CHNGME         # The ircDDB username defaults to the value defined for gateway callsign.
password=

# up to 4 repeaters can be added
[Repeater_1]
enabled=true
band=B                  # Each module has to have a band letter
callsign=              # Has to be less than 8 characters, if empty gateway call will be used
address=		        # address where the repeater can be found, if left empty defaults to 127.0.0.1
port=20011
type=hb                 # valid values: hb or icom
reflector=
reflectorAtStartup=true    # if reflector is set, this defaults to true
reflectorReconnect=30   # valid values: never, fixed, 5, 10, 15, 20, 25, 30, 60, 90, 120, 180
frequency=438.325
offset=-7.6
rangeKm=35
latitude=53.03371
longitude=5.66113
agl=16
description1=Repeater Sneek.
description2=Friesland
url=
band1=
band2=
band3=

[Repeater_2]
enabled=false
band=			# Each module has to have a band letter
callsign=		# Has to be less than 8 characters, if empty gateway call will be used
address=		# address where the repeater can be found, if left empty defaults to 127.0.0.1
port=20012
type=hb			# hb or icom
reflector=dcs007b
reflectorAtStartup=true
reflectorReconnect=30 # never, fixed, 5, 10, 15, 20, 25, 30, 60, 90, 120, 180
frequency=434.0
offset=-1.6
rangeKm=20
latitude=0.0
longitude=0.0
agl=
description1=
description2=
url=
band1=
band2=
band3=

[Repeater_3]
enabled=false
band=			# Each module has to have a band letter
callsign=		# Has to be less than 8 characters, if empty gateway call will be used
address=		# address where the repeater can be found, if left empty defaults to 127.0.0.1
port=20013
type=hb			# hb or icom
reflector=
reflectorAtStartup=true
reflectorReconnect=30 # never, fixed, 5, 10, 15, 20, 25, 30, 60, 90, 120, 180
frequency=434.0
offset=-1.6
rangeKm=20
latitude=0.0
longitude=0.0
agl=
description1=
description2=
url=
band1=
band2=
band3=

[Repeater_4]
enabled=false
band=			# Each module has to have a band letter
callsign=		# Has to be less than 8 characters, if empty gateway call will be used
address=		# address where the repeater can be found, if left empty defaults to 127.0.0.1
port=20014
type=hb			# hb or icom
reflector=
reflectorAtStartup=true
reflectorReconnect=30 # never, fixed, 5, 10, 15, 20, 25, 30, 60, 90, 120, 180
frequency=434.0
offset=-1.6
rangeKm=20
latitude=0.0
longitude=0.0
agl=
description1=
description2=
url=
band1=
band2=
band3=

[APRS]
enabled=true
hostname=server.pd2rld.nl   # Defaults to rotate.aprs2.net
port=14580                  # Defaults to 14580, there is no reason to change this
password=23731
positionSource=fixed           # Sets how the position is determined fixed or gpsd. this is ignored if DStargateway was built without GPSD support

[GPSD]
address=                  # GPSD address, defaults to 127.0.0.1
port=                     # GPSD port, defaults to 2947

[Log]
path=/var/log/dstargateway/
fileRoot=       # defaults to dstarGateway
fileRotate=     # rotate log files daily, defaults to true
fileLevel=      # defaults to info, valid values are trace, debug, info, warning, error, fatal, none
displayLevel=   # defaults to info, valid values are trace, debug, info, warning, error, fatal, none
repeatThreshold=#defaults to 2, valid values are disbaled and 1 to 10. Prevents flooding of logs from repeated log messages.

[Paths]
data=/usr/local/share/dstargateway.d/ #Path where the data (hostfiles, audio files etc) can be found

[DExtra]
enabled=true # There is no reason to disable this
maxDongles=5

[DPlus]
enabled=true # There is no reason to disable this
maxDongles=5
login= # defaults to gateway callsign

[DCS]
enabled=true # There is no reason to disable this

[XLX]
enabled=true 
hostfileUrl=http://xlxapi.rlx.lu/api.php?do=GetXLXDMRMaster

[DRats]
enabled=false # Defaults to false. The program need to be compiled with DRats support for DRats to be actually enabled

[Remote]
enabled=false
port=4242
password=CHANGE_ME # If password is left blank, remote will be disabled regardless of the enabled field

# Should only be used with respect to your local regulation! Many countries prohibit setting up private repeaters !
[AccessControl]
whiteList= # Only affects network
blackList= # Only affects network
restrictList= # Only affects RF, call signs present in this list are now allowed to change reflector or unlink the repeater

# The Provided install routines install the program as a systemd unit. SystemD does not recommand "old-school" forking daemons nor does systemd
# require a pid file. Moreover systemd handles the user under which the program is started. This is provided as convenience for people who might
# run the program using sysv or any other old school init system.
[Daemon]
daemon=false
pidfile=/var/run/dstargateway/dstargateway.pid # pid file is in our case useless when running as a daemon  using systemd as systemd takes care of the service not being started twice
user=dstar # user account the daemon will run under, ideally a user with low privileges. Switching to this user will only happen when the program is started as root
***@***.***:/usr/local/etc $ 



Verzonden vanuit Mail voor Windows

Van: Geoffrey Merck
Verzonden: woensdag 17 juli 2024 22:29
Aan: F4FXL/DStarGateway
CC: pa2snk; Author
Onderwerp: Re: [F4FXL/DStarGateway] DTMF not working and dstargateway.servicedoes not start (Issue #48)

If changing reflector on Icom stack is working and not working on homebrew, it might be related to this issue here: g4klx/MMDVMHost#702

**Comment by pa2snk** [comment]
the users dstar is not made during the install process, i changed user to mmdvm and the gateway is working fine now as i added this user this week so multiple systems can run on the same raspberry.

**Comment by F4FXL** [comment]
Please open a separate issue for the user creation.
