### ISSUE TITLE
Automatically Update Hosts files

### ISSUE THREAD

**Issue by coolacid** [F4FXL/DStarGateway#50]
Code appears to already exist for getting the XLX hosts files. It would be fantastic if instead of needing to download the hosts files externally, if DStarGateway could periodically download all the hosts files and reload if successful, this would help ensure repeaters always have the latest files.

**Comment by F4FXL** [comment]
Currently the update of the XLX only happens at start. I think if we go down that road, we shoudl also add a timer to refresh the host files every X hours or days.

**Comment by F4FXL** [comment]
@coolacid Looking for suggestions.
XLX is being downloaded to a temporary file. The files in /usr/local/etc/ I am considering doing it a similar way for other files this ignoring the host files in /usr/local/etc/
If the user switches auto update off, only the files in /usr/local/etc will be used.
any thoughts?

**Comment by coolacid** [comment]
My opinion;

- There should be a configured directory. Configuration should probably default to `/usr/local/etc/` 
- Configuration can enable auto-update or disable, this would download into the configured directory
- There should be a second configured directory with any overloads. 

The application would apply the data from the system directory first, then apply any entries from an overload directory.

This would allow an internal system to update on a regular cadence, but allow a system administrator to apply either private or other changes beyond the system default.

**Comment by F4FXL** [comment]
I had some discussion with other sysops.
Some said they would like to have all of the auto download removed and rather only have DStarGateway monitor the files for change and reload them in case files were changed.
The reason is they use some handmade scripts which check for the download, patch/add some hosts and then have the script restart the gateway.
They also pointed out that sometimes host files lag behind the routing network, especially for non reflector hosts. Re-downloading the host files will then override the newest information that came through ircddb.

**Comment by coolacid** [comment]
Yep, that use case of being able to add/update hosts outside of the normal download lists is why I suggested the second configured directory with over loads. 

This allows a sysop to take any reflector ID, and point it at a specific hostname/IP address. I'd suggest that even if the reflector ID is listed in the main lists, the overload files would overwrite internally. 

This is what some of the hotspot devices do, have a download that downloads the main files, then applies changes based on a different directory.

**Comment by F4FXL** [comment]
Implemented download of host files in this branch https://github.com/F4FXL/DStarGateway/tree/feature/auto_host_file_update_%2350
Still missing custom host files and auto update. Any tests are welcome :)

**Comment by coolacid** [comment]
I have this building at our repeater site now. I'll give it a go. Thanks!

**Comment by coolacid** [comment]
Something that might be worth adding is accepting a HUP or USR1 signal to ask dstargateway to update. This would allow people that manage add-on lists to just send the signal instead of having to do a full restart.

**Comment by IvanGirderboot** [comment]
Related to this topic, is this repo open to adding open-dht support for this info? This is used in urfd and m17 reflectors already to handle this info and moving away from host files (but both can live side-by-side)  
https://github.com/n7tae/ham-dht-tools

**Comment by F4FXL** [comment]
@IvanGirderboot Please open a separate topic for this.

**Comment by coolacid** [comment]
@IvanGirderboot there is already a topic for this #41

**Comment by F4FXL** [comment]
Indeed .... oops.... Still working on this one, I expect to have something in the next days, depending on the workload at the daytime job.

**Comment by F4FXL** [comment]
This is ready for more testing. 24hours timeout is yet hardcoded. 
Support for custom hosts files
Reload of hosts files on  USR1 signal

**Comment by coolacid** [comment]
```
[2024-09-16 22:44:54] [INFO   ] Caught signal : User defined signal 1, updating host files
[2024-09-16 22:44:54] [INFO   ] Updating hosts files from internet
[2024-09-16 22:44:54] [INFO   ] Downloading host file from http://www.pistar.uk/downloads/DExtra_Hosts.txt
[2024-09-16 22:44:54] [INFO   ] Downloading host file from http://www.pistar.uk/downloads/DCS_Hosts.txt
[2024-09-16 22:44:54] [INFO   ] Downloading host file from http://www.pistar.uk/downloads/DPlus_Hosts.txt
[2024-09-16 22:44:54] [INFO   ] Downloading host file from http://xlxapi.rlx.lu/api.php?do=GetXLXDMRMaster
```

So far so good - Thank you for your work!

**Comment by F4FXL** [comment]
Thanks for your feedback.
I still need to make the download timeout configurable and I'm thinking about having a special section for the host file paths in the configuration file.

**Comment by F4FXL** [comment]
Moved hostsfiles configuration to own config section
Download Timeout is configurable
I talked to some oither sysops and will not implement watch of customHostFiles. It is beter for people to send USR1 when they are done updating their files

**Comment by F4FXL** [comment]
IMHO this feature is ready to be pushed to develop
@coolacid do see any open topics ?

**Comment by coolacid** [comment]
LGTM - Anything beyond is probably a bug. Thanks for the hard work!
