### ISSUE TITLE
DStarGateway/SGS-XL

### ISSUE THREAD

**Issue by riggs498** [F4FXL/DStarGateway#52]
Good afternoon,

I got tired of WPSD and pi-star. It has been acting very weird. So I wanted to kep my repeater D-Star only. I came across you layout and like it so far. I came across a weird problem I have been fighting all day. 

I have SGS-XL running in on my cloud server. STN093C SWOH Talk TG STN093 T Terminate. I am running bot quadnet and ircddb logins. From my radio I send an STN093 C. SGS says it saw my login. I can not get anything back from the SGS server all the time. It does say new host at my hotspot wan ip. The dstargateway software will tell me that N8MFN  C is unknown (not in cache) and then it stops taking information. MMDVMHost still works. But I can not get dstargateway to work. I have to restart that process. Once restarted. It works till it gets an unknown call again. I am wondering if it is an unknown call issues or a STARNET issue in the code of dstarrepeater or something else.

I am confused so I wanted to reach out.

**Comment by F4FXL** [comment]
Hi,

is port 40000 reachable from the outside world on all machines? 
I am confused, is N8MFN your repeater call sign? Can you post your dstargateway config (make sure you redact any passwords) ?

**Comment by F4FXL** [comment]
Also, which branch of DStarGateway are you running?

**Comment by riggs498** [comment]
Everything crashed. I could not get mmdvmhost and dstargateway to talk to eachother again. I wipe the whole thing. I will try again.

**Comment by F4FXL** [comment]
Ok, I am still interested to know the outcome ;)
