### ISSUE TITLE
Support UR linking to XLX repeaters

### ISSUE THREAD

**Issue by coolacid** [F4FXL/DStarGateway#53]
When trying to use a UR command to link to an XLX repeater, the following message shows up in logs:

```
[2024-10-06 22:38:11] [INFO   ] VE3YCA   is trying to G2 route to reflector XLXCA1L , ignoring
[2024-10-06 22:38:27] [INFO   ] VE3YCA   is trying to G2 route to reflector XLXCA1L , ignoring
```

It would be better for the system to identify we're trying to connect to an XLX repeater and route as expected.

**Comment by coolacid** [comment]
And, I missed the module when trying to connect. I'm a dummy. Closing.

**Comment by F4FXL** [comment]
L needs to be the last character, otherwise it is interpreted as a callsign routing attempt.
